# Generated by Django 4.1.2 on 2022-12-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figurinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Informe o tipo da figurinha.', max_length=100)),
                ('nome', models.CharField(help_text='Informe o nome.', max_length=100)),
                ('codigo', models.CharField(help_text='Informe o código correspondente à figurinha. Ex: BRA5', max_length=100)),
                ('pais', models.CharField(help_text='Informe o país.', max_length=100)),
                ('quantidade', models.IntegerField(help_text='Informe quantas figurinhas você dispõe.')),
            ],
        ),
    ]
